"""
Character record data model
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean, Index
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class CharacterRecord(Base):
    """Character record model"""
    __tablename__ = 'character_records'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    conversation_id = Column(String(100), nullable=False, index=True, comment='Conversation ID')
    name = Column(String(200), nullable=False, comment='Character name')
    is_main = Column(Boolean, default=False, nullable=False, comment='Whether this is a main character')
    is_unavailable = Column(Boolean, default=False, nullable=False, comment='Whether this character is unavailable (dead, etc.)')
    first_appeared_message_id = Column(Integer, nullable=True, comment='ID of the message where this character first appeared')
    first_appeared_at = Column(DateTime, nullable=False, default=datetime.utcnow, comment='When this character first appeared')
    is_auto_generated = Column(Boolean, default=False, nullable=False, comment='Whether this character was auto-generated by AI')
    notes = Column(Text, nullable=True, comment='Additional notes about the character')
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, comment='Creation timestamp')
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False, comment='Update timestamp')
    
    __table_args__ = (
        Index('idx_conversation_name', 'conversation_id', 'name'),
    )
    
    def to_dict(self) -> dict:
        """Convert to dictionary"""
        return {
            'id': self.id,
            'conversation_id': self.conversation_id,
            'name': self.name,
            'is_main': self.is_main,
            'is_unavailable': self.is_unavailable,
            'first_appeared_message_id': self.first_appeared_message_id,
            'first_appeared_at': self.first_appeared_at.isoformat() if self.first_appeared_at else None,
            'is_auto_generated': self.is_auto_generated,
            'notes': self.notes,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None
        }

