import { AppSettings } from './index';

export const ENV_CONFIG = {
  // Use Vite's built-in DEV mode instead of custom env variable
  VITE_DEV_MODE: import.meta.env.DEV,
} as const;

export const DEFAULT_SETTINGS: AppSettings = {
  general: {
    language: 'zh',
    autoStart: false,
    minimizeToTray: true,
    startWithSystem: false,
  },
  appearance: {
    theme: 'dark',
    fontSize: 'medium',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  ai: {
    provider: 'ollama',
    ollama: {
      provider: 'ollama',
      baseUrl: 'http://localhost:11434',
      model: 'llama2',
      timeout: 120000,
      maxTokens: 2048,
      temperature: 0.7,
    },
    deepseek: {
      provider: 'deepseek',
      baseUrl: 'https://api.deepseek.com',
      model: 'deepseek-chat',
      timeout: 60000,
      maxTokens: 2048,
      temperature: 0.7,
      apiKey: '',
    },
    openai_compatible: {
      provider: 'openai_compatible',
      baseUrl: 'http://127.0.0.1:1234/v1',
      model: 'gpt-4o-mini',
      timeout: 120000,
      maxTokens: 2048,
      temperature: 0.7,
      apiKey: '',
    },
    openai: {
      provider: 'openai',
      baseUrl: 'https://api.openai.com',
      model: 'gpt-4o-mini',
      timeout: 120000,
      maxTokens: 2048,
      temperature: 0.7,
      apiKey: '',
    },
    azure: {
      provider: 'azure',
      baseUrl: 'https://example-resource.openai.azure.com/openai/v1',
      model: 'gpt-4o-mini',
      timeout: 120000,
      maxTokens: 2048,
      temperature: 0.7,
      apiKey: '',
    },
    anthropic: {
      provider: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      model: 'claude-3-5-sonnet-latest',
      timeout: 120000,
      maxTokens: 2048,
      temperature: 0.7,
      apiKey: '',
    },
    glm: {
      provider: 'glm',
      baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
      model: 'glm-4-flash',
      timeout: 120000,
      maxTokens: 2048,
      temperature: 0.7,
      apiKey: '',
    },
    kimi: {
      provider: 'kimi',
      baseUrl: 'https://api.moonshot.cn',
      model: 'moonshot-v1-8k',
      timeout: 120000,
      maxTokens: 2048,
      temperature: 0.7,
      apiKey: '',
    },
    minimax: {
      provider: 'minimax',
      baseUrl: 'https://api.minimax.chat',
      model: 'MiniMax-Text-01',
      timeout: 120000,
      maxTokens: 2048,
      temperature: 0.7,
      apiKey: '',
    },
  },
  advanced: {
    enableStreaming: false,
    apiTimeout: 120000,
    maxRetries: 3,
    logLevel: 'info',
    enableDiagnostics: false,
    enableAnonymousTelemetry: false,
    enableFreeformNote: false,
  },
  profiles: [],
  activeProfileId: undefined,
};
