import React, { useState, useEffect } from 'react';
import { ConversationSettings, CharacterRecord } from '@/types';
import { useI18n } from '@/i18n';
import { useConversationClient } from '@/hooks/useConversationClient';
import styles from './StorySettingsView.module.scss';

interface StorySettingsViewProps {
  conversationId: string;
  settings: ConversationSettings | null;
  onEdit: () => void;
  onClose: () => void;
}

const StorySettingsView: React.FC<StorySettingsViewProps> = ({
  conversationId,
  settings,
  onEdit,
  onClose,
}) => {
  const { t } = useI18n();
  const conversationClient = useConversationClient();
  const [appearedCharacters, setAppearedCharacters] = useState<CharacterRecord[]>([]);
  const [loadingCharacters, setLoadingCharacters] = useState(false);

  useEffect(() => {
    const loadCharacters = async () => {
      try {
        setLoadingCharacters(true);
        const chars = await conversationClient.getCharacters(conversationId, true);
        setAppearedCharacters(chars);
      } catch (error) {
        console.error('Failed to load characters:', error);
      } finally {
        setLoadingCharacters(false);
      }
    };

    if (conversationId) {
      loadCharacters();
    }
  }, [conversationId, conversationClient]);

  if (!settings) {
    return null;
  }

  const availableCharacters = appearedCharacters.filter(c => !c.is_unavailable);
  const unavailableCharacters = appearedCharacters.filter(c => c.is_unavailable);

  return (
    <div className={styles.overlay} onClick={onClose}>
      <div className={styles.modal} onClick={(e) => e.stopPropagation()}>
        <div className={styles.header}>
          <h2>{t('storySettings.titleAndOutline')}</h2>
          <div className={styles.headerActions}>
            <button onClick={onEdit} className={styles.editButton}>
              {t('storySettings.edit')}
            </button>
            <button onClick={onClose} className={styles.closeButton}>
              ×
            </button>
          </div>
        </div>

        <div className={styles.content}>
          {settings.title && (
            <div className={styles.section}>
              <h3>{t('storySettings.titleLabel')}</h3>
              <p>{settings.title}</p>
            </div>
          )}

          {settings.background && (
            <div className={styles.section}>
              <h3>{t('storySettings.background')}</h3>
              <p className={styles.textContent}>{settings.background}</p>
            </div>
          )}

          {settings.characters && settings.characters.length > 0 && (
            <div className={styles.section}>
              <h3>{t('storySettings.characterRoles')}</h3>
              <div className={styles.charactersList}>
                {settings.characters.map((char, index) => (
                  <div key={index} className={styles.characterItem}>
                    <strong>{char}</strong>
                    {settings.character_personality?.[char] && (
                      <span className={styles.personality}>
                        {settings.character_personality[char]}
                      </span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {settings.outline && (
            <div className={styles.section}>
              <h3>{t('storySettings.outline')}</h3>
              <p className={styles.textContent}>{settings.outline}</p>
            </div>
          )}

          {!loadingCharacters && appearedCharacters.length > 0 && (
            <div className={styles.section}>
              <h3>{t('storySettings.appearedCharacters')}</h3>
              {availableCharacters.length > 0 && (
                <div>
                  <h4 style={{ fontSize: '14px', marginBottom: '8px' }}>
                    {t('storySettings.availableCharacters')}
                  </h4>
                  <div className={styles.charactersList}>
                    {availableCharacters.map((char) => (
                      <div key={char.id} className={styles.characterItem}>
                        <strong>{char.name}</strong>
                        {char.is_main && (
                          <span style={{ marginLeft: '8px', fontSize: '12px', color: '#888' }}>
                            ({t('storySettings.mainCharacter')})
                          </span>
                        )}
                        {char.is_auto_generated && (
                          <span style={{ marginLeft: '8px', fontSize: '12px', color: '#888' }}>
                            ({t('storySettings.autoGenerated')})
                          </span>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}
              {unavailableCharacters.length > 0 && (
                <div style={{ marginTop: '16px' }}>
                  <h4 style={{ fontSize: '14px', marginBottom: '8px' }}>
                    {t('storySettings.unavailableCharacters')}
                  </h4>
                  <div className={styles.charactersList}>
                    {unavailableCharacters.map((char) => (
                      <div key={char.id} className={styles.characterItem} style={{ opacity: 0.6 }}>
                        <strong>{char.name}</strong>
                        {char.notes && (
                          <span style={{ marginLeft: '8px', fontSize: '12px' }}>
                            ({char.notes})
                          </span>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {!settings.background && !settings.characters?.length && !settings.outline && (
            <div className={styles.empty}>
              <p>{t('storySettings.noSettings')}</p>
              <button onClick={onEdit} className={styles.addButton}>
                {t('storySettings.addSettings')}
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default StorySettingsView;

